```{r}
#Importa dados, string vazio como NA, string como fatores
dados = read.csv("Churn.csv", sep=";", na.strings="", stringsAsFactors = T)
head(dados)
summary((dados))
```
Colunas
```{r}
#Dar nomes corretos as colunas
colnames(dados) = c("Id","Score","Estado","Genero","Idade","Patrimonio","Saldo","Produtos","TemCarCredito",
                   "Ativo","Salario","Saiu")
head(dados)
```
Explorar Dados, colunas categóricas
```{r}
#Estados
counts = table(dados$Estado)
barplot(counts,main="Estados", xlab="Estados") # Gráfico de barras
#Genero
counts = table(dados$Genero)
barplot(counts,main="Gêneros", xlab="Gêneros")
```
Explorar, colunas numéricas
```{r}
#Score
summary(dados$Score)
boxplot(dados$Score)
hist(dados$Score)
```
Idade
```{r}
summary(dados$Idade)
boxplot(dados$Idade)
hist(dados$Idade)
```
Saldo
```{r}
summary(dados$Saldo)
boxplot(dados$Saldo)
hist(dados$Saldo)
```

Salário
```{r}
summary(dados$Salario)
boxplot(dados$Salario)
hist(dados$Salario)
```

Valores Faltantes - NAs
```{r}
dados[!complete.cases(dados),]
```

Salários
```{r}
#Tratar salários
summary(dados$Salario)
#Ver mediana
median(dados$Salario,na.rm= T)
#Atribuir mediana a NAs
dados[is.na(dados$Salario),]$Salario = median(dados$Salario, na.rm = T)
#Buscar NAs em salario para checar
dados[!complete.cases(dados$Salario),]
```

Falta da padronização em Gênero
```{r}
#Ver valores
unique(dados$Genero)
summary(dados$Genero)
#Transformar F e Fem em feminino
# NAs, M em Masculino (moda)
dados[is.na(dados$Genero) | dados$Genero == "M",]$Genero = "Masculino"
dados[dados$Genero == "F" | dados$Genero == "Fem",]$Genero = "Feminino"
#Ver resultado
summary(dados$Genero)
#Remover levels não utilizados
dados$Genero = factor(dados$Genero)
#Visualizar novamente
summary(dados$Genero)
```
Idades fora do domínio
```{r}
summary(dados$Idade)
#Fora do domínio, numérico - ver idades anormais
dados[dados$Idade < 0 | dados$Idade > 110,]$Idade
#Não temos idade NAs
dados[is.na(dados$Idade)]
#Opção, preencher com mediana
median(dados$Idade)
#Substituição
dados[dados$Idade < 0 | dados$Idade > 110,]$Idade = median(dados$Idade)
#Conferindo novamente
dados[dados$Idade < 0 | dados$Idade > 110,]
summary(dados$Idade)
```

Dados duplicados
```{r}
#Buscar dados duplicados pelo ID
x = dados[duplicated(dados$Id),]
x
#Verificamos que o ID 81 está duplicado
#Vamos excluir pelo indíce
dados = dados[-c(82),]

#Buscamos a linha que estava duplicada
dados[dados$Id == x$Id,]
```
Estado fora do domínio
```{r}
#Fora do domínio - categorico
unique(dados$Estado)
summary(dados$Estado)
#Preencher com a moda, RS
dados[!dados$Estado %in% c("RS", "SC", "PR"),]$Estado = "RS"
summary(dados$Estado)
#Removemos os fatores
dados$Estado = factor(dados$Estado)
#Visualziar novamente
summary(dados$Estado)
```
Outliers
```{r}
#Outliers, criando um parametro com desvio padrão
desv = sd(dados$Salario, na.rm = T)
dados[dados$Salario >= 2 *desv,]$Salario
#Outra forma, resultado semelhante, mas sem os NAs
boxplot(dados$Salario)
boxplot(dados$Salario, outline = F)
x = boxplot(dados$Salario)$out
x
#Atualizamos todos para mediana
median(dados$Salario)
dados[dados$Salario >= 2*desv,]$Salario = median(dados$Salario)
#Checamos se sairam os outliers
dados[dados$Salario >= 2*desv,]$Salario
```





